### ISSUE TITLE
Analyze failure causes

### ISSUE THREAD

**Issue by atineoSE** [Malaga-AI/mudocun#5]
During data collection many failures occurred, which are logged as JSON objects in the `outputs/failed` and `outputs-arxiv/failed` directories.

**Tasks**:
- [ ] Collect unique causes for failures (e.g. 400 bad request, rate limit, etc).
- [ ] Group unique causes into categories (e.g. pdf access failure, model failed to generate initial questions, model failed to generate structure output, parsing error, etc).
- [ ] Plot categories for easy interpreting.
- [ ] Create list of recommendations for future experiments, based on findings.
