### ISSUE TITLE
Add examples of generated questions

### ISSUE THREAD

**Issue by atineoSE** [Malaga-AI/mudocun#7]
We'd like to provide some concrete examples of the kind of questions that have been generated, so that users can understand the scope and usefulness at a glimpse.

**Tasks:**
- [ ] Sample random examples by picking generated questions for a document, then locating figure/formula, questions and answer.
- [ ] Cherry-pick a diverse set of examples, ideally at least 10, the more diverse, the better.
- [ ] Validate answers by reading the paper as needed and document if the generated answer was right or not.
- [ ] Add relevant examples including captures of the figures/formulas in a markdown file at `examples/examples.md` and link to it prominently from the `README.md`.
- [ ] Optionally, create a Jupyter notebook with a deeper analysis of concrete examples (see [here](https://github.com/Malaga-AI/mudocun/blob/main/notebooks/prompt_exploration.ipynb) as reference)
