### ISSUE TITLE
Compare with similar datasets

### ISSUE THREAD

**Issue by atineoSE** [Malaga-AI/mudocun#8]
Compare our approach with those found in related iniatives:
* [PDFVQA: A New Dataset for Real-World VQA on PDF Documents](https://arxiv.org/abs/2304.06447)
* [Document Understanding Dataset and Evaluation (DUDE)](https://arxiv.org/abs/2305.08455)

**Tasks:**
- [ ] Summarize main contributions of each paper (feel free to add new ones to the list)
- [ ] List main differences from each approach, for example in a table, in a Markdown document at `related_work.md`
- [ ] Link to this new file from the main `README.md`

Thanks to @abrichr for contributing the research
